[package]
name = "maple"
version = "0.1.0"
edition = "2018"

[dependencies]
sys = { path = "modules/sys" }
triangle_renderer = { path = "modules/triangle_renderer" }

[dependencies.clap]
version = "2.33"
default-features = false

[target.'cfg(windows)'.build-dependencies]
embed-resource = "1.6"

[workspace]
members = [
    "modules/vulkan",
    "modules/utils",
    "modules/win32",
    "modules/sys",
]
