[package]
name = "maple"
version = "0.1.0"
edition = "2018"

[dependencies]
sys = { path = "modules/sys" }
renderer = { path = "modules/renderer" }

[dependencies.clap]
version = "2.33.3"
default-features = false

[target.'cfg(windows)'.build-dependencies]
embed-resource = "1.6.3"

[workspace]
members = [
    "modules/renderer",
    "modules/sys",
    "modules/utils",
    "modules/vulkan_utils",
    "modules/win32",
]
