[package]
name = "pal"
version = "0.1.0"
edition = "2018"

[dependencies]
ash = { version = "0.32.1", default-features = false }

[target.'cfg(windows)'.dependencies]
windows = "0.17.2"

[target.'cfg(windows)'.build-dependencies]
windows = "0.17.2"
