[package]
name = "triangle_renderer"
version = "0.1.0"
edition = "2018"

[dependencies]
ash = { version = "0.33", default-features = false }
vulkan_utils = { path = "../vulkan_utils" }
sys = { path = "../sys" }
utils = { path = "../utils" }

[build-dependencies]
shaderc = "0.7"
