[package]
name = "vulkan_utils"
version = "0.1.0"
edition = "2018"

[dependencies]
ash = { version = "0.33", default-features = false }
sys = { path = "../sys" }
utils = { path = "../utils" }
thiserror = "1.0.26"
